#!/usr/bin/env sh

echo 'ffc-ffd-landing-page' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-landing-page/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-ffd-auth' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-auth/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-ffd-business' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-business/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-ffd-proxy' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-proxy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-ffd-ingress' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-ingress/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-ffd-ahwr-stub' &&
  curl --silent "https://api.github.com/repos/defra/ffc-ffd-ahwr-stub/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
